<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE program [
	<!ELEMENT program (oddaja+)>
	<!ELEMENT oddaja (id,num,date,kategorija,title1,title2,tip,izpostavljeno,image)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT num (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT kategorija (#PCDATA)>
	<!ELEMENT title1 (#PCDATA)>
	<!ELEMENT title2 (#PCDATA)>
	<!ELEMENT tip (#PCDATA)>
	<!ELEMENT izpostavljeno (#PCDATA)>
	<!ELEMENT image (#PCDATA)>
	<!ELEMENT url (#PCDATA)>
]>
<program>
	<oddaja>
		<id>107562</id>
		<num>1</num>
		<date>2019-07-04 05:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Egipt - Zimbabve]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107563</id>
		<num>1</num>
		<date>2019-07-04 06:50:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Nigerija - Burundi]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107564</id>
		<num>1</num>
		<date>2019-07-04 08:50:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Senegal - Tanzanija]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107565</id>
		<num>1</num>
		<date>2019-07-04 10:40:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Slonokoščena obala - Južna Afrika]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107566</id>
		<num>1</num>
		<date>2019-07-04 12:30:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Kamerun - Gvineja Bissau]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107751</id>
		<num>1</num>
		<date>2019-07-04 14:30:00</date>
		<kategorija><![CDATA[Nogometne zgodbe]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[7. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107570</id>
		<num>1</num>
		<date>2019-07-04 15:00:00</date>
		<kategorija><![CDATA[MX2]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Nemčije, prva dirka]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[7nz36ymyts_MX2.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107569</id>
		<num>1</num>
		<date>2019-07-04 16:00:00</date>
		<kategorija><![CDATA[MX2]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Nemčije, druga dirka]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[7nz36ymyts_MX2.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107631</id>
		<num>1</num>
		<date>2019-07-04 17:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Nemčije, prva dirka]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107571</id>
		<num>1</num>
		<date>2019-07-04 17:45:00</date>
		<kategorija><![CDATA[ISSF Svetovno prvenstvo Lonato]]></kategorija>
		<title1><![CDATA[Strelstvo]]></title1>
		<title2><![CDATA[Trap, mešani pari]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107572</id>
		<num>1</num>
		<date>2019-07-04 19:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Brazilija - Argentina]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107573</id>
		<num>1</num>
		<date>2019-07-04 21:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Čile - Peru]]></title2>
		<tip><![CDATA[danes]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107574</id>
		<num>1</num>
		<date>2019-07-04 23:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Egipt - Demokratična republika Kongo]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107575</id>
		<num>1</num>
		<date>2019-07-05 01:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Senegal - Alžirija]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107576</id>
		<num>1</num>
		<date>2019-07-05 03:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Maroko - Slonokoščena obala]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107578</id>
		<num>1</num>
		<date>2019-07-05 05:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Kamerun - Gana]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107579</id>
		<num>1</num>
		<date>2019-07-05 06:45:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Madagaskar - Nigerija]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107580</id>
		<num>1</num>
		<date>2019-07-05 08:45:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Uganda - Egipt]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107581</id>
		<num>1</num>
		<date>2019-07-05 10:30:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Južna Afrika - Maroko]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107582</id>
		<num>1</num>
		<date>2019-07-05 12:30:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Kenija - Senegal]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107583</id>
		<num>1</num>
		<date>2019-07-05 14:15:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Benin - Kamerun]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107584</id>
		<num>1</num>
		<date>2019-07-05 16:15:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Angola - Mali]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107585</id>
		<num>1</num>
		<date>2019-07-05 17:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Maroko - Benin]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107587</id>
		<num>1</num>
		<date>2019-07-05 20:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Uganda - Senegal]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107588</id>
		<num>1</num>
		<date>2019-07-05 23:00:00</date>
		<kategorija><![CDATA[Celinski pokal]]></kategorija>
		<title1><![CDATA[Smučarski skoki]]></title1>
		<title2><![CDATA[VN Kranja, 1. tekma]]></title2>
		<tip><![CDATA[danes]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107589</id>
		<num>1</num>
		<date>2019-07-06 01:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Brazilija - Argentina]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107590</id>
		<num>1</num>
		<date>2019-07-06 03:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Čile - Peru]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107633</id>
		<num>1</num>
		<date>2019-07-06 05:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Maroko - Benin]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107634</id>
		<num>1</num>
		<date>2019-07-06 07:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[Motokros Magazin, VN Nemčije]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107635</id>
		<num>1</num>
		<date>2019-07-06 07:30:00</date>
		<kategorija><![CDATA[Celinski pokal]]></kategorija>
		<title1><![CDATA[Smučarski skoki]]></title1>
		<title2><![CDATA[VN Kranja, 1. tekma]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107636</id>
		<num>1</num>
		<date>2019-07-06 09:25:00</date>
		<kategorija><![CDATA[Celinski pokal]]></kategorija>
		<title1><![CDATA[Smučarski skoki]]></title1>
		<title2><![CDATA[VN Kranja, 2. tekma]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107637</id>
		<num>1</num>
		<date>2019-07-06 11:30:00</date>
		<kategorija><![CDATA[Truck Racing]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Hungaroring, vrhunci]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107638</id>
		<num>1</num>
		<date>2019-07-06 12:00:00</date>
		<kategorija><![CDATA[Nogometne zgodbe]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[7. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107639</id>
		<num>1</num>
		<date>2019-07-06 12:30:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Brazilija - Argentina]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107640</id>
		<num>1</num>
		<date>2019-07-06 14:15:00</date>
		<kategorija><![CDATA[Ferrari Challenge Europe 2019]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Trofeja Pirelli, Nurburgring, prva dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107641</id>
		<num>1</num>
		<date>2019-07-06 15:15:00</date>
		<kategorija><![CDATA[Xtreme Collxtion]]></kategorija>
		<title1><![CDATA[Ekstremni športi]]></title1>
		<title2><![CDATA[27. oddaja]]></title2>
		<tip><![CDATA[prvič]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107642</id>
		<num>1</num>
		<date>2019-07-06 15:45:00</date>
		<kategorija><![CDATA[Worldies]]></kategorija>
		<title1><![CDATA[Ekstremni športi]]></title1>
		<title2><![CDATA[15. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107643</id>
		<num>1</num>
		<date>2019-07-06 15:50:00</date>
		<kategorija><![CDATA[Ferrari Challenge Europe 2019]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Pokal Shell, Nurburgring, prva dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107644</id>
		<num>1</num>
		<date>2019-07-06 17:00:00</date>
		<kategorija><![CDATA[Sanjsko moštvo]]></kategorija>
		<title1><![CDATA[Magazin]]></title1>
		<title2><![CDATA[32. oddaja]]></title2>
		<tip><![CDATA[prvič]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107645</id>
		<num>1</num>
		<date>2019-07-06 17:30:00</date>
		<kategorija><![CDATA[Nogometne zgodbe]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[8. oddaja]]></title2>
		<tip><![CDATA[prvič]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107646</id>
		<num>1</num>
		<date>2019-07-06 17:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Nigerija - Kamerun]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107647</id>
		<num>1</num>
		<date>2019-07-06 20:00:00</date>
		<kategorija><![CDATA[WRC]]></kategorija>
		<title1><![CDATA[Reli]]></title1>
		<title2><![CDATA[Vrhunci polsezone]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[0ugscad4oa_WRC.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107648</id>
		<num>1</num>
		<date>2019-07-06 20:55:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Tekma za 3. mesto: Argentina - Čile]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107649</id>
		<num>1</num>
		<date>2019-07-06 23:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Egipt - Južna Afrika]]></title2>
		<tip><![CDATA[danes]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107650</id>
		<num>1</num>
		<date>2019-07-07 01:00:00</date>
		<kategorija><![CDATA[Serie A]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Roma - Napoli]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[anypz1k57x_seriea.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107651</id>
		<num>1</num>
		<date>2019-07-07 03:00:00</date>
		<kategorija><![CDATA[Serie A]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Fiorentina - Torino]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[anypz1k57x_seriea.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107652</id>
		<num>1</num>
		<date>2019-07-07 05:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Nigerija - Kamerun]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107653</id>
		<num>1</num>
		<date>2019-07-07 07:00:00</date>
		<kategorija><![CDATA[MX2]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, prva dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[7nz36ymyts_MX2.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107654</id>
		<num>1</num>
		<date>2019-07-07 08:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, prva dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107673</id>
		<num>1</num>
		<date>2019-07-07 09:00:00</date>
		<kategorija><![CDATA[3,4, Šport]]></kategorija>
		<title1></title1>
		<title2><![CDATA[Studio]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107656</id>
		<num>1</num>
		<date>2019-07-07 10:00:00</date>
		<kategorija><![CDATA[MX2]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, druga dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[7nz36ymyts_MX2.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107657</id>
		<num>1</num>
		<date>2019-07-07 11:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, druga dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107658</id>
		<num>1</num>
		<date>2019-07-07 12:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Tekma za 3. mesto: Argentina - Čile]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107659</id>
		<num>1</num>
		<date>2019-07-07 14:00:00</date>
		<kategorija><![CDATA[Worldies]]></kategorija>
		<title1><![CDATA[Ekstremni športi]]></title1>
		<title2><![CDATA[15. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107660</id>
		<num>1</num>
		<date>2019-07-07 14:15:00</date>
		<kategorija><![CDATA[Ferrari Challenge Europe 2019]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Pokal Shell, Nurburgring, druga dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107661</id>
		<num>1</num>
		<date>2019-07-07 15:15:00</date>
		<kategorija><![CDATA[Xtreme Collxtion]]></kategorija>
		<title1><![CDATA[Ekstremni športi]]></title1>
		<title2><![CDATA[27. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107662</id>
		<num>1</num>
		<date>2019-07-07 15:45:00</date>
		<kategorija><![CDATA[Worldies]]></kategorija>
		<title1><![CDATA[Ekstremni športi]]></title1>
		<title2><![CDATA[16. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107663</id>
		<num>1</num>
		<date>2019-07-07 15:50:00</date>
		<kategorija><![CDATA[Ferrari Challenge Europe 2019]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Trofeja Pirelli, Nurburgring, druga dirka]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107664</id>
		<num>1</num>
		<date>2019-07-07 17:00:00</date>
		<kategorija><![CDATA[WRC]]></kategorija>
		<title1><![CDATA[Reli]]></title1>
		<title2><![CDATA[Vrhunci polsezone]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[0ugscad4oa_WRC.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107665</id>
		<num>1</num>
		<date>2019-07-07 17:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Madagaskar - Demokratična republika Kongo]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107666</id>
		<num>1</num>
		<date>2019-07-07 20:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, prva dirka]]></title2>
		<tip><![CDATA[danes]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107667</id>
		<num>1</num>
		<date>2019-07-07 21:00:00</date>
		<kategorija><![CDATA[MXGP]]></kategorija>
		<title1><![CDATA[Motokros]]></title1>
		<title2><![CDATA[VN Indonezije, druga dirka]]></title2>
		<tip><![CDATA[danes]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[nt27b0dpdc_MXGP.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107668</id>
		<num>1</num>
		<date>2019-07-07 21:55:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Finale: Brazilija - Peru]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107669</id>
		<num>1</num>
		<date>2019-07-08 00:00:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Alžirija - Gvineja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107670</id>
		<num>1</num>
		<date>2019-07-08 02:00:00</date>
		<kategorija><![CDATA[Serie A]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Inter - Lazio]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[anypz1k57x_seriea.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107671</id>
		<num>1</num>
		<date>2019-07-08 04:00:00</date>
		<kategorija><![CDATA[Truck Racing]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Hungaroring, vrhunci]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107672</id>
		<num>1</num>
		<date>2019-07-08 04:30:00</date>
		<kategorija><![CDATA[Nogometne zgodbe]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[8. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107674</id>
		<num>1</num>
		<date>2019-07-08 05:00:00</date>
		<kategorija><![CDATA[Serie A]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Genoa - Inter]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[anypz1k57x_seriea.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107675</id>
		<num>1</num>
		<date>2019-07-08 06:45:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Madagaskar - Demokratična republika Kongo]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107676</id>
		<num>1</num>
		<date>2019-07-08 08:45:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Alžirija - Gvineja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107677</id>
		<num>1</num>
		<date>2019-07-08 10:30:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Brazilija - Argentina]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107678</id>
		<num>1</num>
		<date>2019-07-08 12:30:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Polfinale: Čile - Peru]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107679</id>
		<num>1</num>
		<date>2019-07-08 14:15:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Tekma za 3. mesto: Argentina - Čile]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107680</id>
		<num>1</num>
		<date>2019-07-08 16:00:00</date>
		<kategorija><![CDATA[Copa America]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Finale: Brazilija - Peru]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[gnqr3obt1z_Copa America.JPG]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107681</id>
		<num>1</num>
		<date>2019-07-08 17:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Mali - Slonokoščena obala]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107682</id>
		<num>1</num>
		<date>2019-07-08 20:00:00</date>
		<kategorija><![CDATA[Chantilly Arts and Elegance Richard Mille]]></kategorija>
		<title1><![CDATA[Avtomobilizem]]></title1>
		<title2><![CDATA[Vrhunci]]></title2>
		<tip><![CDATA[prvič]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107683</id>
		<num>1</num>
		<date>2019-07-08 20:30:00</date>
		<kategorija><![CDATA[Sanjsko moštvo]]></kategorija>
		<title1><![CDATA[Magazin]]></title1>
		<title2><![CDATA[32. oddaja]]></title2>
		<tip><![CDATA[ponovitev]]></tip>
		<izpostavljeno>0</izpostavljeno>
		<image><![CDATA[default.jpg]]></image>
		<url><![CDATA[]]></url>
	</oddaja>
	<oddaja>
		<id>107684</id>
		<num>1</num>
		<date>2019-07-08 20:55:00</date>
		<kategorija><![CDATA[Afriški pokal narodov]]></kategorija>
		<title1><![CDATA[Nogomet]]></title1>
		<title2><![CDATA[Osmina finala: Gana - Tunizija]]></title2>
		<tip><![CDATA[živo]]></tip>
		<izpostavljeno>0</izpostavljeno>